behaviors:
  Snake:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 20480
      learning_rate: 1e-4
      learning_rate_schedule: linear
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 20000000
    time_horizon: 256
    summary_freq: 50000
    keep_checkpoints: 5
    checkpoint_interval: 50000